# Configuración corregida para MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=organigrama_db
app.mongo.demo-data=false

# Apagamos los Beans relacionales para que no molesten si Postgres está apagado
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration