server.port=8080

# 1. ACTIVAR LA PERSISTENCIA EN MONGO
app.storage=mongo
app.tree-strategy=custom

# 2. EL TRUCO PARA QUE POSTGRES NO ARRUINE EL ARRANQUE
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# 3. CONEXIÓN DIRECTA A TU CONTENEDOR DE DOCKER
spring.data.mongodb.uri=mongodb://localhost:27017/organigrama_db
app.mongo.demo-data=true