# ===================================================================
# CONFIGURACIÓN GENERAL DEL SERVIDOR
# ===================================================================
server.port=8080

# ===================================================================
# INTEGRANTE A (CHRISTIAN) - CONFIGURACIÓN PARA MOTOR EN MEMORIA
# ===================================================================
app.storage=memory
app.tree-strategy=custom

# ===================================================================
# INTEGRANTE B (JOSE) - CONFIGURACIÓN POSTGRESQL (JPA)
# ===================================================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/organigrama
# spring.datasource.username=postgres
# spring.datasource.password=tu_contraseña
# spring.jpa.hibernate.ddl-auto=update

# ===================================================================
# INTEGRANTE C (ELDER) - CONFIGURACIÓN MONGODB (NOSQL)
# ===================================================================
# spring.data.mongodb.uri=mongodb://localhost:27017/organigrama