server.port=8080

# 1. Estrategia de algoritmos (collections o custom)
app.tree-strategy=collections

# 2. Interruptor central de base de datos o memoria
app.storage=mongo

# 3. Incluye automáticamente el perfil de base de datos elegido
spring.profiles.include=${app.storage}

# 4. Documentación de Swagger activa
springdoc.paths-to-match=/api/v1/**