server.port=8080

# 1. Tu estrategia de algoritmos
app.tree-strategy=custom

# 2. Tu interruptor central (Elige entre: postgres o mongo)
app.storage=mongo

# Mapea e incluye automáticamente el archivo properties correspondiente
spring.profiles.include=${app.storage}